CHROME = 'chrome'
FIREFOX = 'firefox'
EDGE = 'edge'
ENVIRONMENTS_FILE_PATH = 'resources/environments.json'

ASSET_LIST_GAME = 'asset_list_game'
ASSET_LIST_NON_GAME = 'asset_list_non_game'
YOUTUBE_HUB = 'youtube_hub'
ASSET_SEARCH = 'asset_search'
ASSET_UPLOAD = 'asset_upload'
JUNO_HUB = 'juno_hub'
PHOTO_SHOOT_LIBRARY = 'photo_shoot_library'
CHANNEL_READY_LIBRARY = 'channel_ready_library'
LOGIN = 'login'
CORE = 'core'
